// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoBanking.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoBanking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NeoBankingDbContext))]
    [Migration("20260515100709_AddHoppaApiLogDirection")]
    partial class AddHoppaApiLogDirection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("neobanking")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoBanking.Domain.Entities.AdminProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsBreakGlass")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("CompanyInstallationId", "Role");

                    b.ToTable("admin_profiles", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RiskProfileJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("CompanyInstallationId", "EmailNormalized")
                        .IsUnique();

                    b.HasIndex("CompanyInstallationId", "Status");

                    b.ToTable("users", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ActorIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TraceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.HasIndex("CompanyInstallationId", "OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_log_entries", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.BankingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("AvailableBalanceMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long?>("CurrentBalanceMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("SourceHash");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyInstallationId", "UserId", "AsOf");

                    b.HasIndex("CompanyInstallationId", "Provider", "ProviderReference", "SnapshotType", "AsOf")
                        .IsUnique();

                    b.ToTable("banking_snapshots", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.CompanyInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("company_installations", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.HoppaApiCallLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("AppPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AppQueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("AppRequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("AppResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("AppStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("outbound");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("HoppaDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("HoppaEndpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("HoppaMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("HoppaQueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("HoppaRequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("HoppaResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("HoppaStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("TraceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.HasIndex("CompanyInstallationId", "OccurredAt");

                    b.HasIndex("Direction", "OccurredAt");

                    b.HasIndex("HoppaEndpoint", "OccurredAt");

                    b.HasIndex("Succeeded", "OccurredAt");

                    b.ToTable("hoppa_api_call_logs", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("CompanyInstallationId", "Scope", "Key")
                        .IsUnique();

                    b.HasIndex("CompanyInstallationId", "Status", "LockedUntil");

                    b.ToTable("idempotency_records", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.KybVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BeneficialOwnersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("BusinessProfileJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentChecksJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OnboardingApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskSignalsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("OnboardingApplicationId");

                    b.HasIndex("CompanyInstallationId", "RegistrationNumber");

                    b.HasIndex("CompanyInstallationId", "Status");

                    b.HasIndex("CompanyInstallationId", "Provider", "ProviderReference");

                    b.ToTable("kyb_verifications", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.KycVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentChecksJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("OnboardingApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskSignalsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("OnboardingApplicationId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyInstallationId", "Provider", "ProviderReference");

                    b.HasIndex("CompanyInstallationId", "UserId", "Status");

                    b.ToTable("kyc_verifications", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.OnboardingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicantUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("CompanyInstallationId", "Kind", "Status");

                    b.ToTable("onboarding_applications", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.PaymentCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillingAddressJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Bin")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("ExpiryMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpiryYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderCardId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SpendingControlsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyInstallationId", "LastFour");

                    b.HasIndex("CompanyInstallationId", "Provider", "ProviderCardId")
                        .IsUnique();

                    b.HasIndex("CompanyInstallationId", "UserId", "Status");

                    b.ToTable("cards", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.ProviderMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderEntityId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ProviderEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SyncStateJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("CompanyInstallationId", "InternalEntityType", "InternalEntityId");

                    b.HasIndex("CompanyInstallationId", "Provider", "ProviderEntityType", "ProviderEntityId")
                        .IsUnique();

                    b.ToTable("provider_mappings", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RotatedFromTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyInstallationId", "UserId", "ExpiresAt");

                    b.ToTable("refresh_sessions", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailAtProvider")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("UserId", "IsPrimary");

                    b.HasIndex("CompanyInstallationId", "Provider", "Subject")
                        .IsUnique();

                    b.ToTable("user_identities", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WebhookEndpointId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("WebhookEndpointId");

                    b.HasIndex("CompanyInstallationId", "Provider", "EventId")
                        .IsUnique();

                    b.HasIndex("CompanyInstallationId", "Status", "NextAttemptAt");

                    b.ToTable("webhook_deliveries", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("EventTypesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInstallationId");

                    b.HasIndex("CompanyInstallationId", "Status");

                    b.HasIndex("CompanyInstallationId", "Provider", "Url")
                        .IsUnique();

                    b.ToTable("webhook_endpoints", "neobanking");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.AdminProfile", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("NeoBanking.Domain.Entities.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("Users")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.BankingSnapshot", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithMany("BankingSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyInstallation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.HoppaApiCallLog", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("IdempotencyRecords")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.KybVerification", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.OnboardingApplication", "OnboardingApplication")
                        .WithMany("KybVerifications")
                        .HasForeignKey("OnboardingApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyInstallation");

                    b.Navigation("OnboardingApplication");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.KycVerification", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.OnboardingApplication", "OnboardingApplication")
                        .WithMany("KycVerifications")
                        .HasForeignKey("OnboardingApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithMany("KycVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");

                    b.Navigation("OnboardingApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.OnboardingApplication", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "ApplicantUser")
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("OnboardingApplications")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantUser");

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.PaymentCard", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.ProviderMapping", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("ProviderMappings")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.RefreshSession", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.UserIdentity", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany()
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoBanking.Domain.Entities.WebhookEndpoint", "WebhookEndpoint")
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyInstallation");

                    b.Navigation("WebhookEndpoint");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("NeoBanking.Domain.Entities.CompanyInstallation", "CompanyInstallation")
                        .WithMany("WebhookEndpoints")
                        .HasForeignKey("CompanyInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyInstallation");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("AuditLogs");

                    b.Navigation("BankingSnapshots");

                    b.Navigation("Cards");

                    b.Navigation("Identities");

                    b.Navigation("KycVerifications");

                    b.Navigation("RefreshSessions");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.CompanyInstallation", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("IdempotencyRecords");

                    b.Navigation("OnboardingApplications");

                    b.Navigation("ProviderMappings");

                    b.Navigation("Users");

                    b.Navigation("WebhookEndpoints");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.OnboardingApplication", b =>
                {
                    b.Navigation("KybVerifications");

                    b.Navigation("KycVerifications");
                });

            modelBuilder.Entity("NeoBanking.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
